Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Security/MarshalLoad:
  Exclude:
    - lib/site-inspector/disk_cache.rb
