#! /usr/bin/env ruby

require 'csv'
require 'open-uri'
require "./lib/site-inspector"

url = "https://explore.data.gov/api/views/ku4m-7ynp/rows.csv?accessType=DOWNLOAD"
data = open(url).read

domains = []
i = 0
CSV.new(data, headers: true).each_with_index do |row, index|
  puts "Processing #{row["Domain Name"]}..."
  begin
    site = SiteInspector.new(row["Domain Name"])
    if site.redirect?
      domain = {
        :domain => site.domain.to_s,
        :uri => site.uri.to_s,
        :government => site.government?,
        :live => !!site.response,
        :ssl => site.https?,
        :enforce_https => site.enforce_https?,
        :non_www => site.non_www?,
        :redirect => site.redirect,
        :ip => site.ip,
        :hostname => site.hostname.to_s,
      }
    else
      domain = site.as_json
      [:cms, :analytics, :javascript, :advertising].each do |field|
        domain[field] = domain[field].keys.join(", ")
      end
    end
    domain[:agency] = row["Federal Agency "]
    domains.push domain
  rescue Exception => msg
    puts "#{row["Domain Name"]} errored out: #{msg} :("
  end
end

CSV.open("data.csv", "wb", headers: true, write_headers: true) do |csv|
  csv << domains.first.keys
  domains.each do |domain|
    csv << domain.values
  end
end
